# Generated by Django 4.2.4 on 2023-09-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
