# Generated by Django 4.2.4 on 2023-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_is_varified_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
